version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/scanner_db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  profile_scanner:
    build:
      context: .
      dockerfile: docker/scanner.Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/scanner_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  boost_scanner:
    build:
      context: .
      dockerfile: docker/scanner.Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/scanner_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  pair_scanner:
    build:
      context: .
      dockerfile: docker/scanner.Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/scanner_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  pool_scanner:
    build:
      context: .
      dockerfile: docker/scanner.Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/scanner_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scanner_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: